version: '3.7'

services:
  openalpr:
    image: quay.io/shal/openalpr-web
    restart: on-failure
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: alpr.robot.shanaakh.pro'
      traefik.port: 8080

  robot:
    image: quay.io/shal/robot
    restart: on-failure
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      RIA_API_KEY: "${RIA_API_KEY}"
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./bot.json:/tmp/bot.json

  proxy:
    image: traefik
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/acme.json:/acme.json
      - ./config/traefik.toml:/etc/traefik/traefik.toml:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: dashboard.robot.shanaakh.pro'
      traefik.port: 8080
